services:
  web: &web
    build:
      dockerfile: ./docker/image/Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - ./:/site
      - ./docker/image/root/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/image/root/supervisor.d:/etc/supervisor.d
      - ./docker/image/root/php-overrides.ini:/etc/php/conf.d/overrides.ini
      - ./docker/image/root/php-overrides.local.ini:/etc/php/conf.d/overrides.local.ini
    env_file: .env
    ports:
      - 80
    environment:
      VIRTUAL_HOST: nntmux.local
      IS_DOCKER: "true"
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      TZ: ${APP_TZ}
    depends_on:
      - mariadb
      - redis
      - manticore

  tmux:
    <<: *web
    stdin_open: true
    tty: true
    environment:
      IS_DOCKER: "true"
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      TZ: ${APP_TZ}
      COLUMNS: "`tput cols`"
      LINES: "`tput lines`"
    command: /site/cli/docker tmux-start
    depends_on:
      - mariadb
      - redis
      - manticore

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - $PWD/docker/image/root/redis-data;/data

  manticore:
    image: manticoresearch/manticore
    restart: unless-stopped
    volumes:
      - $PWD/docker/image/root/manticore-data;/var/lib/manticore/data

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    volumes:
      - $PWD/docker/image/root/mariadb-data:/var/lib/mysql
      - $PWD:/var/www/NNTmux/
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${APP_TZ}
