name: Build and push docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build
        run: docker build -t ghcr.io/bodrick/newznab-tmux:latest ./docker/image

      - name: Docker push
        run: docker push ghcr.io/bodrick/newznab-tmux:latest
